### ISSUE TITLE
Skeleton of the Material System

### ISSUE THREAD

**Issue by MechOrigin** [elizabethlfransen/SecretlyComplicated#3]
## Skeleton of the Material System
---

1. What we're looking for is the [Gregtech](https://github.com/GregTech-Intergalactical/GregTech) and [Antimatter API](https://github.com/GregTech-Intergalactical/AntimatterAPI) material system, such as dust, impure dust, nugget, ingot, raw, plate, rod, wire, gem, block, gear, dense plate, etc. As well as mekanisms ore processing: crystals, etc
    - Digging some material types in Gregtech sourcecode I found: ORE, CRUSHED, CRUSHED_PURIFIED, CRUSHED_CENTRIFUGED, DUST_IMPURE, DUST_PURE, RAW_ORE, ORE_SMALL, LENS, GEM_BRITTLE, GEM_POLISHED, PLATE, ROD, DUST, DUST_SMALL, DUST_TINY, INGOT, NUGGET, BLOCK, DENSE_PLATE, GEAR, WIRE
    - I love how they dynamically created colors for every material and used just 1 texture/overlay. It saves a lot on space and load time. I hate that Emendatus Enigmatica uses a different texture for EVERY material. Totally unnecessary, I can make it look good and not use up 4000kb (compressed jar).
    - Fluids should be included as well, I have mixed feelings about how Gregtech labels all fluids, for example: Liquid Copper. As scientifically it has a liquid form: [solid, liquid, gas, plasma] but I really like how metals are labeled Molten in EE, for example: Molten Copper. I think we should use scientific labeling [solid, liquid, gas, plasma] though despite that, what do you think?
    - We need every element (maybe? Not sure why we'd need every heavy element though) in the periodic table, in their 3 forms, solid, liquid, gas (high priority).
    - Need Anti matter variants of the first 4 elements, as well as respective atomic particles [positron, anti-proton] in gas form (low priority).
    - Need alloys, I couldn't find an ENUM or an array of them (also didnt look hard) but in loading up the game I made a basic list of some [here](https://github.com/MechOrigin/NTC3/blob/master/kubejs/server_scripts/NTC3/constants/general.js) (high priority). I know I left some out like Blue and Red alloy for example because they exceeded 3 input materials, but we should really add them (low priority)
    - Need isotopes of a few common materials, refer to all the nuclearcraft isotopes.
    - Need diatomic, of lithium (dilithium or Li2), as well as states of it all the way to decalithium (Li10) [I have plans]. We can use the IUPAC numerical multiplier for reference on prefix.

2. Also looking for a rock strata type system like [Project Rankine](https://github.com/CannoliCatfish/project-rankine) where there are various igneous, metamorphic, sedimentary materials, but the main thing is the STRATA generation.
    - Upon digging I found this [Base Properties](https://github.com/CannoliCatfish/project-rankine/blob/93517a2ff22d4a64ccbca2d2f1b85c9d481c2cc4/src/main/java/com/cannolicatfish/rankine/init/RankineBlocks.java#L114) which lists every type of block material. The ones that we're most interested in are things that sort of overlap the gregtech materials like cassiterite, bauxite, sphalerite, etc. Another thing to note is that at this point we don't want to worry about polished, slabs, etc. Only the stones such as: PEGMATITE, GRAY_GRANITE, RHYOLITE, COMENDITE, GRANODIORITE, etc (these were just some igneous btw). Here are some images: [strata](https://media.forgecdn.net/attachments/thumbnails/436/419/310/172/2022-02-27_15.png), [strata2](https://media.forgecdn.net/attachments/thumbnails/436/418/310/172/2022-02-27_15.png)
    - I plan to contribute heavily on code for both, but priority at the moment is getting materials like gears and plates, impure dust, etc. So I can work on unifying again for NTC3.

3. I can work on all the textures, no problem!

4. I know gas support is tricky, this depends on if we decide to use mekanism machines solely or use custom machine types as well with gas support. A hacky way around it that I used for NTC in some instances was just creating it a fluid instead and calling it a gas.

**Comment by elizabethlfransen** [comment]
Do we plan on using alchemistry?

**Comment by elizabethlfransen** [comment]
See https://github.com/elizabethlfransen/SecretlyComplicated/milestone/1
