### ISSUE TITLE
Create Chemicals

### ISSUE THREAD

**Issue by elizabethlfransen** [elizabethlfransen/SecretlyComplicated#5]
We should create all known chemicals on the periodic table in the three main phases of matter. It should be simple to register a new chemical specifying the atomic number, name, and color

**Comment by MechOrigin** [comment]
I love this idea, I was looking at how kotlin creates enums and I saw that you can associate constructors to enums like: 
```
    enum class CardType(val color: String) {
    SILVER("gray"),
    GOLD("yellow"),
    PLATINUM("black")
}
```
